### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by edugm94** [SpriteMisaka/PyLDL#2]
Hello,

I am trying to run this code, however, I am having problems with my Tensorflow configuration. I normally work with PyTorch, so, I had to install TF. 
Could you please share the version you used? or what requirements are needed? 

Thanks in advance!

**Comment by SpriteMisaka** [comment]
Hello,

I am glad to share the requirements. Basically you need these:

numpy==1.22.3
matplotlib==3.6.1
qpsolvers==4.0.0
quadprog==0.1.11
scikit-fuzzy==0.4.2
scikit-learn==1.0.2
scipy==1.8.0
tensorflow-gpu==2.8.0
tensorflow-probability==0.16.0

If you want to load the original implementation, follow the steps in `README.txt`.

Let me know if anything is missing. Thanks!

**Comment by edugm94** [comment]
Hello,

Thanks for your response. I am trying to run some easy code you put in `README.txt` but it is impossible. It crashes when executing this line of code: 
```
from algorithms import _BaseLDL, _BaseLE
import tensorflow_probability as tfp
```
And this is the error I got: _AttributeError: module 'tensorflow.python.framework.type_spec' has no attribute '_NAME_TO_TYPE_SPEC'_

I do not know if this has to do with my tensorflow installation. I am having issues with the NVIDIA drivers, and I installed the CPU version. 

Is there something I am missing? 
Thanks!

**Comment by SpriteMisaka** [comment]
I have no idea. But please try installing Keras==2.8.0.

**Comment by SpriteMisaka** [comment]
> I have no idea. But please try installing Keras==2.8.0.

Hello,

Is this helpful? I'm still waiting for your response.

**Comment by edugm94** [comment]
Sorry, I fix it in another way. But thanks for your support.
