### ISSUE TITLE
SJAFFE dataset images

### ISSUE THREAD

**Issue by edugm94** [SpriteMisaka/PyLDL#3]
Hello, 

I wanted to use the dataset SJAFFE. There are 213 samples which correspond to 213 images of the dataset. Is there any way to know which sample id corresponds to each image from the original dataset?  

Thanks in advance!

**Comment by SpriteMisaka** [comment]
Hi,

I happened to make a list according to the label distributions of SJAFFE. Could you leave your email address so I can send it to you?

**Comment by edugm94** [comment]
Here it is: eduardo.gutierrez-maestro@oru.se 

Thanks so much!
